name: CI/CD pipeline

env:
  MONGO_URI: ${{ secrets.MONGO_URI }}
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: |
          echo "Starting deployment on Vercel (TODO...)"
